---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^series_favoritas_de_ana\\s*$"
  - "^series_favoritas_de_hector\\s*$"
  - ^\[\s*\"hola\"\s*\,\s*\"mundo\!\"\s*\]\s*$
  - ^\[\s*\"hola\"\s*\,\s*\"hola\"\s*\]\s*$
name: Series favoritas
