---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - ^list\.index\s*\(\s*dias_laborales\s*\,\s*\"osvaldo\"\s*\)\s*$
name: "¿Y dónde está?"
