---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - ^\[\s*\"hola\"\s*\,\s*\"mundo\"\s*\]\s*\=\=\s*\[\s*\"mundo\"\s*\,\s*\"hola\"\s*\]\s*$
  - ^\[\s*\"hola\"\s*\,\s*\"mundo\"\s*\]\s*\=\=\s*\[\s*\"hola\"\s*\,\s*\"todo\"\s*\,\s*\"el\"\s*\,\s*\"mundo\"\s*\]\s*$
  - ^\[\s*\"hola\"\s*\]\s*\=\=\s*\[\s*\"hola\"\s*\,\s*\"mundo\"\s*\]\s*$
  - ^\[\s*\"hola\"\s*\,\s*\"mundo\"\s*\]\s*\=\=\s*\[\s*\"hola\"\s*\,\s*\"mundo\"\s*\]\s*$
name: Y esto es una lista
