---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^numeros_de_loteria\\s*$"
  - "^salio_cara\\s*$"
  - "^tiradas_del_dado\\s*$"
  - "^lista_de_listas\\s*$"
name: Juegos de azar
