---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^len\\s*\\(\\s*\\[\\s*\\]\\s*\\)\\s*$"
  - "^len\\s*\\(\\s*\\[\\s*4\\s*\\,\\s*4\\s*\\]\\s*\\)\\s*$"
  - "^len\\s*\\(\\s*\\[\\s*\\[\\s*1\\s*\\,\\s*2\\s*\\]\\s*\\,\\s*\\[\\s*8\\s*\\]\\s*\\,\\s*\\[\\s*14\\s*\\,\\s*87\\s*\\]\\s*\\]\\s*\\)\\s*$"
  - "^len\\s*\\(\\s*numeros_de_loteria\\s*\\)\\s*$"
name: "¿Cuántos elementos tenés?"
